apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd
  source:
    repoURL: https://github.com/initishgupta/flora-apps.git
    path: charts/argo-cd
    targetRevision: HEAD
  destination:
    server: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
